namespace: btc-platform

ingress:
  enabled: true
  className: nginx
  host: ""

serviceA:
  image:
    repository: ghcr.io/NoamTrabelsi/service-a
    tag: "1.0.0"

serviceB:
  image:
    repository: ghcr.io/NoamTrabelsi/service-b
    tag: "1.0.0"
